<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class StoreAddressPost extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'tag' => 'present',
            'consignee_name' => 'required|string|between:2,15',
            'consignee_mobile' => 'required|string|size:11',
            'province' => 'required|string',
            'city' => 'required|string',
            'district' => 'required|string',
            'detail' => 'required|string'
        ];
    }

    public function messages()
    {
        return [
            'tag.present' => '表单数据非法，未包含[标签]信息',
            'consignee_name.required' => '需要指定[收件人姓名]',
            'consignee_name.between' => '[收件人姓名]长度须在2-15个字符之间',
            'consignee_mobile.required' => '需要指定[收件人手机号码]',
            'consignee_mobile.size' => '[收件人手机号码]长度须为11位',
            'province.required' => '需要指定[省份]',
            'city.required' => '需要指定[地市]',
            'district.required' => '需要指定[区县]',
            'detail.required' => '需要指定[详细地址]'
        ]; // TODO: Change the autogenerated stub
    }
}
